### PR TITLE
Meged base branch to be pulled into the main branch

### PR DESCRIPTION
**Pull request by erezfree29**
We have created an exact clone of a New York Times article.
Languages used are HTML for Markup and CSS.
this project was created using continuous integration and test to ensure high quality of code.

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @erezfree29 and @vidhishweta01  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

* [ ] Please, make all the changes as requested by the previous TSE.
* [ ] The NYT logo in the navbar is too small.
* [ ] The background colour of the navbar should be white
* [ ] The editor's pick section is at the wrong place. 
* [ ] The first image on the page should have a short description
* [ ] The **Theory of inflation section** is messed up. Kindly fix it.
* [ ] Elements are to be aligned with a combination of all three techniques ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) and ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements#introduction)) 

### Make the required changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by erezfree29** [comment]
Changed implemented

**Comment by vidhishweta01** [comment]
changes were implemented as per the code review

**Review by Georjane — APPROVED** [review]
## Status: PR Approved 💯 🥇 
### Hi Team✋🏽 
Nice work. Your project meets the minimum requirements for it to be approved. It's a thumbs up for me. 👍🏽 You can go ahead and merge this pull request.🤝 

Good luck on your next project and Happy Coding 💻

**Pull request merged**
